# Generated by Django 3.0.6 on 2020-05-22 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('given_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('prefix_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='CholesterolPractitioner',
            fields=[
                ('chol_prac_id', models.IntegerField(primary_key=True, serialize=False)),
                ('average_cholesterol', models.IntegerField(default=0)),
                ('filter_cholesterol', models.IntegerField(default=0)),
                ('refresh_rate', models.IntegerField(default=30000)),
                ('original_practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_practitioner', to='app.Practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='CholesterolPatient',
            fields=[
                ('chol_patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latest_chol', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('highlighted', models.BooleanField(default=False)),
                ('original_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_patient', to='app.Patient')),
            ],
        ),
    ]
