# Generated by Django 3.0.6 on 2020-05-22 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200522_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cholesterolpatient',
            name='original_patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='original_patient', to='app.Patient'),
        ),
    ]
