# Generated by Django 3.0.6 on 2020-06-12 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200522_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressurePractitioner',
            fields=[
                ('bp_prac_id', models.IntegerField(primary_key=True, serialize=False)),
                ('filter_bp', models.IntegerField(default=0)),
                ('refresh_rate', models.IntegerField(default=30000)),
                ('original_practitioner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bp_original_practitioner', to='app.Practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressurePatient',
            fields=[
                ('bp_patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latest_sys_bp', models.IntegerField(default=0)),
                ('latest_dia_bp', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('highlighted', models.BooleanField(default=False)),
                ('original_patient', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bp_original_patient', to='app.Patient')),
            ],
        ),
    ]
