# Generated by Django 3.0.6 on 2020-06-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bloodpressurepatient_latest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cholesterolpatient',
            name='latest_time',
            field=models.CharField(default='', max_length=300),
        ),
    ]
