# Generated by Django 3.0.7 on 2020-06-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_smokerpatient_smokerpractitioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressurepractitioner',
            name='highlighted_dia_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodpressurepractitioner',
            name='highlighted_sys_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cholesterolpractitioner',
            name='above_average_count',
            field=models.IntegerField(default=0),
        ),
    ]
